name = input("Enter the Name")
print(name)
a = len(name)
print(a)
b=name.lower()
print(b)
c=name.swapcase()
print(c)
d=max(name)
print(d)
e=min(name)
print(e)
f=name.lstrip("ak")
print(f)